version: '2'
services:
    myproject-mongodb:
        container_name: myproject-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/myproject/mongodb/:/data/db/
